import test from 'node:test';import assert from 'node:assert/strict';
import {newProject,createControl} from '../src/project/model.js';import {compileWin32} from '../src/native/compiler.js';
import {nativeTabPagePlan} from '../src/native/control-tabs.js';import {PE32Image} from '../src/native/pe32.js';import {NativeX86Machine} from './support/native-x86-machine.mjs';
function project(layout=false){const p=newProject('TabPages'),f=p.modules[0],tab=createControl('SSTab','Pages'),a=createControl('TextBox','A'),b=createControl('TextBox','B'),shared=createControl('Label','Shared');tab.properties.Tabs=[{Caption:'One',Controls:['A']},{Caption:'Two',Controls:['B']}];for(const c of [a,b,shared])c.parent=tab.name;f.form.controls=[tab,a,b,shared];f.code='Private Sub Form_Load()\nA.Visible=False\nPages.Tab=1\nB.Visible=True\nEnd Sub';if(layout)p.settings.anchoring=true;return {p,f,tab,a,b,shared};}
test('tab page plan preserves explicit ownership, captions and shared child behavior without mutation',()=>{const {f,tab}=project(),before=JSON.stringify(f),plan=nativeTabPagePlan(f.form);assert.equal(JSON.stringify(f),before);assert.deepEqual(plan.pages.map(p=>[p.childId,p.page]),[[f.form.controls[1].id,0],[f.form.controls[2].id,1]]);assert.equal(plan.tabs[0].id,tab.id);});
test('raw FRM indexed tab controls resolve exact control-array identities',()=>{const {f,tab,a,b}=project();tab.properties.Tabs=2;tab.properties['TabCaption(0)']='日本';tab.properties['Tab(0).Control(0)']='Text(2)';tab.properties['Tab(0).ControlCount']=1;tab.properties['Tab(1).Control(0)']='Text(9)';tab.properties['Tab(1).ControlCount']=1;a.name=b.name='Text';a.properties.Index=2;b.properties.Index=9;const plan=nativeTabPagePlan(f.form);assert.equal(plan.tabs[0].entries[0].Caption,'日本');assert.deepEqual(plan.pages.map(p=>p.childId),[a.id,b.id]);tab.properties['Tab(1).Control(0)']='Text';assert.throws(()=>nativeTabPagePlan(f.form),/ambiguous/);});
test('tab metadata rejects conflicting pages, missing children and unsupported header state',()=>{for(const change of [x=>x.tab.properties.Tabs[1].Controls.push('A'),x=>x.tab.properties.Tabs[0].Controls.push('Missing'),x=>x.a.properties.TabPage=4,x=>x.tab.properties.Tabs[1].Enabled=0,x=>x.tab.properties['Tab(0).ControlCount']=1]){const x=project();change(x);assert.throws(()=>nativeTabPagePlan(x.f.form),/tab|Tab|page/);}});
for(const optimization of [0,1,2])test(`tab pages compile with layout and omit helpers for unbound tabs at O${optimization}`,()=>{for(const layout of [false,true]){const {p}=project(layout),before=JSON.stringify(p),r=compileWin32(p,{optimization});assert.equal(JSON.stringify(p),before);assert.deepEqual(r.bytes,compileWin32(p,{optimization}).bytes);assert.equal(r.report.controls.runtime.tabPages,2);if(layout)assert.equal(r.report.layout.enabled,true);if(!layout)assert.ok(r.bytes.length<65536);else{const baseline=structuredClone(p);for(const e of baseline.modules[0].form.controls[0].properties.Tabs)delete e.Controls;assert.ok(r.bytes.length-compileWin32(baseline,{optimization}).bytes.length<4096,"page masking stays a small increment over the existing layout kernel");}}const {p,tab}=project();for(const e of tab.properties.Tabs)delete e.Controls;const r=compileWin32(p,{optimization});assert.equal(r.report.controls.runtime.tabPages,0);});
function machine(t,optimization){const {p}=project();let linked;const finish=PE32Image.prototype.finish;t.mock.method(PE32Image.prototype,'finish',function(...args){linked=finish.apply(this,args);return linked;});compileWin32(p,{optimization});const vm=new NativeX86Machine(linked),m=vm.memory,handles={pages:100,a:101,b:102,shared:103},styles=new Map([[100,0x10000000],[101,0x10000000],[102,0x10000000],[103,0x10000000]]),shown=[],focused=[];let selected=0,focus=0,reenter=null;
 for(const [name,hwnd]of Object.entries(handles))m.write(vm.symbol('hwnd:Form1:'+name),hwnd);
 for(const name of ['a','b'])m.write(vm.symbol('native:tab-page:Form1:'+name)+16,1);
 vm.hook('user32.dll','SendMessageW',4,([hwnd,msg])=>{assert.equal(hwnd,100);assert.equal(msg,0x130b);return selected;});
 vm.hook('user32.dll','GetWindowLongW',2,([hwnd,index])=>{assert.equal(index|0,-16);return styles.get(hwnd)||0;});
 vm.hook('user32.dll','ShowWindow',2,([hwnd,show])=>{shown.push([hwnd,show]);styles.set(hwnd,show?0x10000000:0);reenter?.();return 1;});
 vm.hook('user32.dll','IsWindowVisible',1,([hwnd])=>styles.get(hwnd)?1:0);vm.hook('user32.dll','IsWindow',1,([hwnd])=>styles.has(hwnd)?1:0);
 vm.hook('user32.dll','GetFocus',0,()=>focus);vm.hook('user32.dll','IsChild',2,([hwnd,child])=>hwnd===101&&child===999?1:0);
 vm.hook('user32.dll','SetFocus',1,([hwnd])=>{focused.push(hwnd);focus=hwnd;return 1;});
 return {vm,m,styles,shown,focused,setTab:n=>selected=n,setFocus:n=>focus=n,reenter:fn=>reenter=fn,apply:()=>vm.invoke('native:tab:apply',[100]),show:(h,v)=>vm.invoke('native:tab:show',[h,v]),visible:h=>vm.invoke('native:tab:visible',[h])|0};}
for(const optimization of [0,1,2])test(`emitted tab page masking preserves logical Visible and repairs focus at O${optimization}`,t=>{const k=machine(t,optimization);k.apply();assert.deepEqual(k.shown,[[102,0]]);assert.equal(k.visible(102),-1);k.apply();assert.equal(k.shown.length,1,'unchanged pages do not send redundant ShowWindow');k.setFocus(999);k.setTab(1);k.apply();assert.equal(k.styles.get(101),0);assert.equal(k.styles.get(102),0x10000000);assert.deepEqual(k.focused,[100]);k.show(102,0);k.setTab(0);k.apply();k.setTab(1);k.apply();assert.equal(k.visible(102),0);assert.equal(k.styles.get(102),0);k.show(103,0);assert.equal(k.visible(103),0);});
test('emitted page focus repair rejects re-created controls and accepts an empty tab collection',t=>{const k=machine(t,0);k.setFocus(999);k.setTab(-1);k.reenter(()=>{const rec=k.vm.symbol('native:tab-page:Form1:a');k.m.write(rec+16,2);});k.apply();assert.equal(k.focused.length,0);assert.equal(k.styles.get(101),0);assert.equal(k.styles.get(102),0);assert.equal(k.visible(101),-1);});
test('page normalization restores legacy inactive FRM positions only in the export clone',()=>{const {p,tab,a,b}=project();tab.properties.Tabs=2;tab.properties['Tab(0).Control(0)']='A';tab.properties['Tab(1).Control(0)']='B';b.properties.Left=-74700;const before=JSON.stringify(p);const plan=nativeTabPagePlan(p.modules[0].form);assert.equal(plan.pages.find(c=>c.childId===b.id).left,300);assert.equal(plan.pages.find(c=>c.childId===a.id).left,undefined);compileWin32(p);assert.equal(JSON.stringify(p),before);});
test('paged indexed Visible evaluates its receiver only once before the RHS',t=>{
 const p=newProject('IndexedPage'),f=p.modules[0],tab=createControl('SSTab','Pages'),a=createControl('TextBox','A');a.properties.Index=0;a.parent='Pages';tab.properties.Tabs=[{Caption:'One',Controls:['A(0)']}];f.form.controls=[tab,a];
 f.code='Private calls As Long\nPrivate Function Pick() As Long\ncalls=calls+1\nPick=0\nEnd Function\nPrivate Sub Form_Load()\nA(Pick()).Visible=False\nEnd Sub';let linked;const finish=PE32Image.prototype.finish;t.mock.method(PE32Image.prototype,'finish',function(...args){linked=finish.apply(this,args);return linked;});compileWin32(p);const vm=new NativeX86Machine(linked),m=vm.memory;
 for(const [name,value]of [['hwnd:Form1',99],['initialized:Form1',1],['loaded:Form1',1],['hwnd:Form1:pages',100],['hwnd:Form1:a:0',101]])m.write(vm.symbol(name),value);
 vm.hook('user32.dll','SendMessageW',4,()=>0);vm.hook('user32.dll','GetWindowLongW',2,()=>0x10000000);vm.hook('user32.dll','GetFocus',0,()=>0);vm.hook('user32.dll','ShowWindow',2,([hwnd,visible])=>{assert.equal(hwnd,101);assert.equal(visible,0);return 1;});vm.invoke('proc:Form1:Form_Load');assert.equal(m.read(vm.symbol('global:Form1:calls')),1);
});
