import test from 'node:test';import assert from 'node:assert/strict';import {newProject,createControl} from '../src/project/model.js';import {compileWin32} from '../src/native/compiler.js';import {PE32Image} from '../src/native/pe32.js';import {NativeX86Machine} from './support/native-x86-machine.mjs';
function captionMachine(t,optimization=0){const p=newProject('Caption'),f=p.modules[0];f.form.controls=[createControl('SSTab','Pages')];f.code='Private Sub Form_Load()\nDim value As String\nPages.TabCaption(1)="日本"\nvalue=Pages.TabCaption(1)\nPages.TabCaption="Current"\nvalue=Pages.TabCaption\nEnd Sub';let linked;const finish=PE32Image.prototype.finish;t.mock.method(PE32Image.prototype,'finish',function(...args){linked=finish.apply(this,args);return linked;});const result=compileWin32(p,{optimization}),vm=new NativeX86Machine(linked),m=vm.memory,queries=[],captions=['First','Second','Third'];let internal=false,empty=false,fail=false;const out=m.alloc(4,'owned-caption-out');m.write(out,0);
 vm.hook('oleaut32.dll','SysReAllocStringLen',3,([at,src,n])=>{let text='';for(let i=0;src&&i<n;i++)text+=String.fromCharCode(m.read(src+2*i,16));const copy=m.string(text),old=m.read(at);if(old)m.free(old-4);m.write(at,copy);return 1;});
 vm.hook('user32.dll','SendMessageW',4,([hwnd,msg,index,rec])=>{assert.equal(hwnd,100);if(msg===0x1304)return captions.length;assert.ok(index<captions.length);assert.equal(m.read(rec),1);if(fail)return 0;const pointer=m.read(rec+12);if(msg===0x133d){captions[index]=m.utf16(pointer);return 1;}assert.equal(msg,0x133c);const capacity=m.read(rec+16);queries.push(capacity);if(empty)m.write(rec+12,0);else if(internal)m.write(rec+12,internal);else{const text=captions[index].slice(0,capacity-1);for(let i=0;i<text.length;i++)m.write(pointer+2*i,text.charCodeAt(i),16);m.write(pointer+2*text.length,0,16);}return 1;});
 return {vm,m,out,result,captions,queries,returned:ptr=>internal=ptr,noText:()=>empty=true,fail:()=>fail=true,get:i=>vm.invoke('native:tab:caption-get',[100,i,out]),set:(i,text)=>{const b=m.string(text);try{return vm.invoke('native:tab:caption-set',[100,i,b]);}finally{m.free(b-4);}},dispose:()=>{const b=m.read(out);if(b)m.free(b-4);m.write(out,0);}};}
for(const optimization of [0,1,2])test(`native TCITEMW caption setter/getter grows beyond fixed buffers at O${optimization}`,t=>{const k=captionMachine(t,optimization),text='日本'.repeat(3000);k.set(1,text);assert.equal(k.captions[1],text);assert.equal(k.m.bstr(k.get(1)),text);assert.ok(k.queries.length>5);assert.ok(k.queries.at(-1)>6000);k.set(1,'');assert.equal(k.m.bstr(k.get(1)),'');k.dispose();});
test('native caption getter copies replaced pszText and handles a NULL return pointer',t=>{const k=captionMachine(t),text='Returned native pointer 日本',ptr=k.m.string(text);k.returned(ptr);const result=k.get(1);assert.equal(k.m.bstr(result),text);assert.notEqual(result,ptr);assert.equal(k.m.bstr(ptr),text);k.noText();assert.equal(k.m.bstr(k.get(1)),'');k.dispose();k.m.free(ptr-4);});
test('native caption setter diagnoses embedded NUL instead of silently truncating',t=>{const k=captionMachine(t);assert.throws(()=>k.set(1,'abc\0def'),e=>e.number===380);assert.equal(k.captions[1],'Second');});
test('native caption bounds and failed native reads retain an owned cleanup slot',t=>{const k=captionMachine(t);assert.throws(()=>k.get(3),e=>e.number===381);assert.equal(k.m.read(k.out),0);});
test('failed native caption retrieval does not orphan its allocated BSTR',t=>{const k=captionMachine(t);k.fail();assert.throws(()=>k.get(1),e=>e.number===381);assert.ok(k.m.read(k.out));k.dispose();});
