import {xamlEnabled} from '../xaml/contract.js';
import {createRenderingOptions} from '../rendering/settings-ui.js';
import {layoutEnabled,validateLayout} from '../layout/contract.js';
import {hasUIDialog} from '../core/window-context.js';
import {el,clone,lower,download} from '../core/core.js';
import {scanDeclarations,wordAt} from '../editor/intelligence.js';
import {positionAt} from '../editor/projection.js';
import {THEMES,colorValue} from '../theme/theme.js';
import {normalizeIdeAppearance as normalizeAppearance,resolveIdeTheme} from '../theme/ide-appearance.js';
import {createIdeThemeSettings} from './theme-settings.js';
import {createApplicationThemeSettings} from './application-theme-settings.js';
import {addProcedureSource,readProcedureAttributes,updateProcedureAttributes,formatControls} from './procedure-tools.js';
import {modal,alertDialog,tabbedPages} from './ui.js';
const check=(label,value)=>{const input=el('input',{type:'checkbox',checked:!!value});return {input,node:el('label',{class:'option-check'},input,label)};};
const field=(name,value,attrs={})=>el('input',{'aria-label':name,value,...attrs});
const select=(name,items,value)=>{const node=el('select',{'aria-label':name},...items.map(item=>el('option',{value:Array.isArray(item)?item[0]:item},Array.isArray(item)?item[1]:item)));node.value=value;return node;};
const group=(name,...children)=>el('fieldset',{},el('legend',{},name),...children);
export class IdeTools {
 constructor(ide){this.ide=ide;this.buildPalette();}
 async addProcedure(){const ide=this.ide,module=ide.activeModule;if(!module||ide.runState!=='design')return;const original=module.code,name=field('プロシージャ名',''),type=select('種類',['Sub','Function','Property'],'Sub'),scope=select('スコープ',['Public','Private'],'Public'),staticLocals=check('すべてのローカル変数を Static にする',false),body=el('div',{class:'dialog-grid'},el('label',{},'名前:'),name,el('label',{},'種類:'),type,el('label',{},'スコープ:'),scope,staticLocals.node);
 await modal('プロシージャの追加',{width:390,content:body,buttons:[{label:'OK',value:true,primary:true,action:()=>{if(ide.activeModule!==module||module.code!==original||ide.runState!=='design')throw new Error('ダイアログが開いている間にモジュールが変更されました。');const result=addProcedureSource(module,{name:name.value,type:type.value,scope:scope.value,staticLocals:staticLocals.input.checked}),before=clone(ide.project);module.code=result.code;ide.record(before,'プロシージャの追加: '+result.name,false);ide.openDocument(module.id,'code',result.line);return true;}},{label:'キャンセル',value:false}]});}
 async attributes(){const ide=this.ide,module=ide.activeModule;if(!module||ide.runState!=='design')return;const procedures=scanDeclarations(module).procedures,names=[...new Set(procedures.map(p=>p.name))];if(!names.length)return alertDialog('このモジュールにはプロシージャがありません。','プロシージャの属性');const current=procedures.filter(p=>p.line<=ide.editor.cursor().line).at(-1)?.name||names[0],name=select('対象プロシージャ',names,current),description=field('説明','',{maxlength:4096}),help=field('ヘルプ コンテキスト ID',0,{type:'number',min:0,max:2147483647}),id=field('プロシージャ ID',''),hidden=check('オブジェクト ブラウザで非表示にする',false),restricted=check('制限されたメンバー',false),originalCode=module.code,originalAttributes=JSON.stringify(module.attributes||[]);
 const load=()=>{const a=readProcedureAttributes(module,name.value);description.value=a.description;help.value=a.helpContext;id.value=a.memberId??'';hidden.input.checked=a.hidden;restricted.input.checked=a.restricted;};name.addEventListener('change',load);load();
 await modal('プロシージャの属性',{width:520,content:el('div',{class:'procedure-attributes'},el('div',{class:'dialog-grid'},el('label',{},'名前:'),name,el('label',{},'説明:'),description,el('label',{},'ヘルプ コンテキスト ID:'),help),group('詳細',el('div',{class:'dialog-grid'},el('label',{},'プロシージャ ID:'),id),hidden.node,restricted.node),el('p',{class:'tool-note'},'属性はネイティブ ソース メタデータに保存されます。COM ディスパッチおよび Windows Help との統合は提供されません。')),buttons:[{label:'OK',value:true,primary:true,action:()=>{if(ide.activeModule!==module||ide.runState!=='design'||module.code!==originalCode||JSON.stringify(module.attributes||[])!==originalAttributes)throw new Error('ダイアログが開いている間にモジュールが変更されました。');const attributes=updateProcedureAttributes(module,name.value,{description:description.value,helpContext:help.value,memberId:id.value,hidden:hidden.input.checked,restricted:restricted.input.checked}),before=clone(ide.project);module.attributes=attributes;ide.record(before,'プロシージャの属性');return true;}},{label:'キャンセル',value:false}]});
 }
 async options(){const ide=this.ide,initialProject=ide.project,a=normalizeAppearance(ide.appearance),settings=ide.project.settings,checks=new Map(),add=(key,label,value)=>{const item=check(label,value);checks.set(key,item.input);return item.node;},value=key=>checks.get(key).checked;
 const themeSettings=createIdeThemeSettings(a),applicationSettings=createApplicationThemeSettings(settings);
 const tab=field('タブ間隔',settings.tabWidth,{type:'number',min:1,max:32}),font=select('エディタ フォント',['Courier New','Consolas','MS Gothic','monospace'],a.editorFont),size=select('フォント サイズ',[11,12,13,14,16,18,20],a.editorSize),colors={...a.codeColors},theme=themeSettings.select,appTheme=applicationSettings.select,grid=field('グリッド間隔 (twips)',settings.gridSize||120,{type:'number',min:15,max:1200}),backend=select('グラフィックス レンダラー',[['auto','WebGPU (Canvas2D フォールバック付き)'],['canvas2d','Canvas2D']],settings.renderer||'auto');
 const editor=el('div',{},group('コードの設定',add('autoSyntaxCheck','自動構文チェック',a.autoSyntaxCheck),add('requireVariableDeclaration','変数の宣言を強制する',a.requireVariableDeclaration),add('autoListMembers','メンバーの一覧表示',a.autoListMembers),add('autoQuickInfo','クイック ヒント',a.autoQuickInfo),add('autoDataTips','データ ヒント',a.autoDataTips),add('autoIndent','自動インデント',a.autoIndent),el('label',{class:'option-check'},'タブ間隔: ',tab)),group('ウィンドウの設定',add('dragText','ドラッグ＆ドロップ編集',a.dragText),add('fullModule','常にモジュール全体を表示',a.fullModule),add('procedureSeparators','プロシージャの区切り線',a.procedureSeparators)),el('p',{class:'tool-note'},'編集後にフォーカスを奪うことなく自動構文診断が実行されます。利用可能な場合はワーカーが使用されます。'));
 const roles=[['text','通常のテキスト'],['background','コードの背景'],['keyword','キーワード'],['comment','コメント'],['selection','選択範囲の背景'],['selectionText','選択範囲の文字'],['breakpoint','ブレークポイントの背景'],['execution','実行行の背景']],role=select('色の種類',roles,'text'),color=field('色','#000000',{type:'color'}),sample=el('pre',{class:'editor-options-sample','aria-label':'エディタ表示サンプル'}),palette=()=>resolveIdeTheme(themeSettings.value(),!!theme.ownerDocument.defaultView.matchMedia?.('(prefers-color-scheme: dark)').matches).colors,roleMap={text:'windowText',background:'window',selectionText:'selectionText'};
 const samplePaint=()=>{const get=key=>colors[key]||palette()[roleMap[key]||key];sample.style.font=`${size.value}px/${Number(size.value)+4}px "${font.value}",monospace`;sample.style.background=get('background');sample.style.color=get('text');sample.replaceChildren(el('span',{style:{color:get('comment')}},"' これはコメントです\n"),el('span',{style:{color:get('keyword')}},'Public Sub '),'Example()\n    Dim count As Long\n',el('span',{style:{color:get('keyword')}},'End Sub'));color.value=get(role.value);};for(const input of [font,size,theme,role])input.addEventListener('change',samplePaint);color.addEventListener('input',()=>{colors[role.value]=color.value;samplePaint();});themeSettings.onChange(samplePaint);samplePaint();
 const format=el('div',{},group('コードの色',el('div',{class:'dialog-grid'},el('label',{},'色の種類:'),role,el('label',{},'色:'),color),el('button',{type:'button',onclick:()=>{delete colors[role.value];samplePaint();}},'システム カラーを使用'),el('button',{type:'button',onclick:()=>{for(const key of Object.keys(colors))delete colors[key];samplePaint();}},'すべての色をリセット')),el('div',{class:'dialog-grid'},el('label',{},'フォント:'),font,el('label',{},'サイズ:'),size),add('margin','余白インジケーター バー',a.margin),add('lineNumbers','行番号を表示 (ブラウザー拡張)',settings.lineNumbers),sample);
 const errorTrapping=select('エラーのトラップ',[['all','すべてのエラーで中断'],['class','クラス モジュールで中断'],['unhandled','処理されないエラーで中断']],settings.errorTrapping||'unhandled');
 const general=el('div',{},group('配置の拡張機能',add('anchoring','アンカーと自動レイアウトを有効にする (このプロジェクト)',layoutEnabled(ide.project)),add('xaml','XAML フォーム オーサリングを有効にする (このプロジェクト)',xamlEnabled(ide.project)),el('p',{class:'tool-note'},'既定ではオフです。このプロジェクトおよび対応するエクスポートでレイアウト プロパティとデザイナ ツールを有効にします。')),group('エラーのトラップ',errorTrapping),group('フォーム グリッド設定',add('showGrid','グリッドの表示',settings.showGrid!==false),el('label',{class:'option-check'},'グリッド間隔 (twips): ',grid),add('snapToGrid','コントロールをグリッドに合わせる',settings.snapToGrid!==false)),group('外観',el('div',{class:'dialog-grid'},el('label',{},'IDE テーマ:'),theme,el('label',{},'アプリケーション テーマ:'),appTheme,el('label',{},'グラフィックス:'),backend),themeSettings.preferences,themeSettings.preview,themeSettings.note,group('アプリケーションの外観',applicationSettings.preferences,applicationSettings.preview,applicationSettings.note),add('tooltips','ヒントを表示',a.tooltips),add('largeToolbarIcons','大きなツールバー ボタン',a.largeToolbarIcons),add('documentTabs','ドキュメント タブを表示',a.documentTabs)),group('エディット＆コンティニュー',add('notifyStateLoss','状態の喪失前に通知',a.notifyStateLoss)));
 const dockList=el('div',{class:'options-dock-list'}),dockChecks=[];for(const [id,window]of ide.docking.model.windows){const view=ide.docking.panels.get(id),item=check(view.title,window.dockable);item.input.setAttribute('aria-label','ドッキング可能 '+view.title);dockList.append(item.node);dockChecks.push([id,item.input]);}
 const windowMode=select('IDE ウィンドウ モード',[
   ['mdi','インページ MDI のみ'],['hybrid','MDI とブラウザー ウィンドウのハイブリッド']
 ],a.windowMode);
 const docking=el('div',{},group('ウィンドウ モード',el('label',{class:'option-check'},'IDE ウィンドウ モード: ',windowMode),
   el('p',{class:'tool-note'},'インページ MDI はドキュメントの移動、サイズ変更、最小化、最大化、重ねて表示、並べて表示に対応します。')),
 el('p',{},'ドッキング可能なウィンドウを選択します。チェックを外すとブラウザー内でフロート表示されます。'),dockList,el('p',{class:'tool-note'},'タイトル バーを端または他のツール ウィンドウにドラッグします。Ctrl キーを押しながらでドッキングを抑制できます。'));
 // Preserve absent optional defaults so an IDE-only change does not dirty the project or add an undo entry.
 const renderingOptions=createRenderingOptions(ide);
 const apply=()=>{if(ide.project!==initialProject)throw new Error('現在のプロジェクトが変更されました。');const width=Number(tab.value),step=Number(grid.value);if(!Number.isInteger(width)||width<1||width>32)throw new Error('タブ間隔は 1 から 32 の整数で指定してください。');if(!Number.isFinite(step)||step<15||step>1200)throw new Error('グリッド間隔は 15 から 1200 twip の範囲で指定してください。');const before=clone(ide.project),appearance={...a,...themeSettings.value(),windowMode:windowMode.value,codeColors:colors,theme:theme.value,editorFont:font.value,editorSize:Number(size.value)};for(const key of ['autoSyntaxCheck','requireVariableDeclaration','autoListMembers','autoQuickInfo','autoDataTips','autoIndent','dragText','fullModule','procedureSeparators','margin','tooltips','largeToolbarIcons','documentTabs','notifyStateLoss'])appearance[key]=value(key);validateLayout({...ide.project,settings:{...settings,anchoring:value('anchoring')}},false);Object.assign(settings,{xaml:value('xaml'),anchoring:value('anchoring'),errorTrapping:errorTrapping.value,tabWidth:width,gridSize:step,showGrid:value('showGrid'),snapToGrid:value('snapToGrid'),lineNumbers:value('lineNumbers'),renderer:backend.value,theme:appTheme.value});const appAppearance=applicationSettings.value();if(Object.hasOwn(before.settings,'themeOptions')||Object.values(appAppearance.themeOptions).some(Boolean))settings.themeOptions=appAppearance.themeOptions;ide.sendRuntime('applicationAppearance',appAppearance);if(!Object.hasOwn(before.settings,'anchoring')&&!settings.anchoring)delete settings.anchoring;if(!Object.hasOwn(before.settings,'xaml')&&!settings.xaml)delete settings.xaml;if(!Object.hasOwn(before.settings,'errorTrapping')&&settings.errorTrapping==='unhandled')delete settings.errorTrapping;ide.sendRuntime('debuggerOptions',{errorTrapping:errorTrapping.value});if(!Object.hasOwn(before.settings,'lineNumbers')&&!settings.lineNumbers)delete settings.lineNumbers;if(!Object.hasOwn(before.settings,'theme')&&settings.theme==='classic')delete settings.theme;renderingOptions.apply();ide.appearance=normalizeAppearance(appearance);for(const [id,input]of dockChecks)ide.docking.model.setDockable(id,input.checked);ide.docking.render();ide.docking.changed();ide.applyAppearance();ide.commandBars?.render();const withoutAppearance=({theme,themeOptions,...rest})=>JSON.stringify(rest),appearanceOnly=withoutAppearance(before.settings)===withoutAppearance(settings);if(JSON.stringify(before)!==JSON.stringify(ide.project))ide.record(before,'オプション',!appearanceOnly);else if(!appearanceOnly)ide.renderAll();if(appearanceOnly){for(const designer of ide.documents.designers.values()){designer.themeController?.apply(settings);designer.modelRevision=ide.visualRevision;}ide.inspector.refreshApplicationColors();ide.updateTitle();}ide.autosave();return true;};
 try {await modal('オプション',{width:555,content:tabbedPages([{id:'editor',label:'エディタ',node:editor},{id:'format',label:'エディタの書式',node:format},{id:'general',label:'全般',node:general},{id:'docking',label:'ドッキング',node:docking},{id:'rendering',label:'レンダリング',node:renderingOptions.node}],{label:'オプション カテゴリ',selected:'editor'}),buttons:[{label:'OK',value:true,primary:true,action:apply},{label:'キャンセル',value:false}]});} finally {applicationSettings.dispose();}
 }
 buildPalette(){const ide=this.ide,body=el('div',{class:'ide-color-palette'}),target=select('対象プロパティ',[['BackColor','背景色 (BackColor)'],['ForeColor','前景色 (ForeColor)']],'BackColor'),sample=el('div',{class:'ide-palette-sample'},'サンプル'),swatches=el('div',{class:'ide-palette-swatches',role:'toolbar','aria-label':'カラー パレット'});this.paletteTarget=target;const colors=['#000000','#808080','#800000','#808000','#008000','#008080','#000080','#800080','#ffffff','#c0c0c0','#ff0000','#ffff00','#00ff00','#00ffff','#0000ff','#ff00ff'];
 const apply=color=>{sample.style[target.value==='BackColor'?'background':'color']=colorValue(color);if(ide.runState!=='design'||!ide.activeModule?.form){ide.status('パレット色を適用するにはフォームまたはコントロールを選択してください。');return;}ide.setProperty(target.value,color);};for(const [index,hex]of colors.entries()){const rgb=parseInt(hex.slice(1),16),bgr=((rgb&255)<<16)|(rgb&65280)|(rgb>>>16),button=el('button',{type:'button','aria-label':'パレット '+hex,title:hex,style:{background:hex},tabindex:index? -1:0,onclick:()=>apply(bgr)});swatches.append(button);}
 swatches.addEventListener('keydown',e=>{const buttons=[...swatches.children],index=buttons.indexOf(swatches.ownerDocument.activeElement);if(index<0)return;const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:e.key==='ArrowRight'?Math.min(index+1,15):e.key==='ArrowLeft'?Math.max(index-1,0):e.key==='ArrowDown'?Math.min(index+8,15):e.key==='ArrowUp'?Math.max(index-8,0):-1;if(next>=0){e.preventDefault();buttons.forEach((b,i)=>b.tabIndex=i===next?0:-1);buttons[next].focus();}});
 body.append(el('div',{class:'ide-palette-header'},target,sample),swatches,el('button',{type:'button',onclick:()=>apply(target.value==='BackColor'?0x8000000f:0x80000012)},'システム カラー'));const panel=el('section',{class:'ide-color-palette-window'},ide.caption('カラー パレット',()=>ide.docking.show('colorPalette',false)),body);ide.docking.register('colorPalette',panel,{edge:'bottom',hidden:true,title:'カラー パレット'});
 }
 format(command){const ide=this.ide,designer=ide.designer;if(ide.runState!=='design'||!ide.activeModule?.form||designer.locked)return;const controls=designer.selected();if(!controls.length)return;const before=clone(ide.project),changed=formatControls(ide.activeModule.form,controls,command,ide.project.settings.gridSize||120,designer.primaryId);if(changed)ide.record(before,'書式: '+command);}
 async printCode(){const ide=this.ide,module=ide.activeModule;if(!module)return;const range=ide.editor.selectionBounds(),selection=module.code.slice(range.start,range.end),scope=select('印刷範囲',[['module','現在のモジュール'],['project','現在のプロジェクト'],...(selection?[['selection','選択範囲']]:[])],'module'),numbers=check('行番号',true);const yes=await modal('コードの印刷',{width:400,content:el('div',{},el('label',{},'範囲: ',scope),numbers.node,el('p',{class:'tool-note'},'ソース コードのみを含むブラウザーの印刷ウィンドウを開きます。'))});if(!yes)return;const docs=scope.value==='project'?ide.project.modules:[{...module,code:scope.value==='selection'?selection:module.code}],escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),html='<!doctype html><html><meta charset="utf-8"><title>'+escape(ide.project.name)+' — コード</title><style>body{font:12px monospace}section{break-before:page}section:first-child{break-before:auto}pre{white-space:pre-wrap;tab-size:'+Number(ide.project.settings.tabWidth||4)+'}button{font:13px sans-serif}@media print{button{display:none}}</style><button onclick="print()">印刷</button>'+docs.map(m=>'<section><h2>'+escape(m.name)+'</h2><pre>'+escape(numbers.input.checked?m.code.split('\n').map((line,i)=>String(i+1).padStart(5)+'  '+line).join('\n'):m.code)+'</pre></section>').join('')+'</html>';const win=window.open('about:blank','_blank');if(win){win.opener=null;win.document.write(html);win.document.close();}else {download(ide.project.name+'-source-print.html',html,'text/html');ide.status('ポップアップがブロックされたため、印刷用ドキュメントをダウンロードしました。');}}
}
export function installIdeTools(ide){const tools=ide.ideTools=new IdeTools(ide),command=ide.command.bind(ide),menu=ide.menu.bind(ide);ide.optionsDialog=()=>tools.options();ide.command=async(id,...args)=>{if(id==='addProcedure')return tools.addProcedure();if(id==='procedureAttributes')return tools.attributes();if(id==='colorPalette')return ide.docking.show('colorPalette',true);if(id==='printCode')return tools.printCode();if(id.startsWith('format:'))return tools.format(id.slice(7));if(id==='stop'&&ide.runState==='paused'&&ide.appearance.notifyStateLoss){const yes=await modal('プロジェクトのリセット',{width:390,content:el('p',{},'実行を終了すると現在の変数値は破棄されます。終了しますか？')});if(!yes)return;}return command(id,...args);};
 ide.menu=name=>{const items=menu(name),design=ide.runState==='design'&&!!ide.activeModule;if(name==='Tools')items.unshift({id:'addProcedure',label:'プロシージャの追加…',enabled:design},{id:'procedureAttributes',label:'プロシージャの属性…',enabled:design},null);if(name==='View')items.push(null,{id:'colorPalette',label:'カラー パレット'});if(name==='File'){const at=items.findIndex(i=>i?.id==='projectProperties');items.splice(at<0?items.length:at,0,{id:'printCode',label:'コードの印刷…',shortcut:'Ctrl+P',enabled:!!ide.activeModule});}if(name==='Format'){for(const [axis,label]of [['horizontal','水平方向の間隔'],['vertical','垂直方向の間隔']])items.push({label,items:[['Equal','均等に配置'],['Increase','間隔を広げる'],['Decrease','間隔を狭める'],['Remove','間隔をなくす']].map(([suffix,title])=>({id:'format:'+axis+suffix,label:title,enabled:design}))});items.push({label:'フォームの中央に配置',items:[['Horizontal','水平方向'],['Vertical','垂直方向']].map(([axis,title])=>({id:'format:center'+axis+'InForm',label:title,enabled:design}))},{label:'サイズを合わせる',items:[['Grid','グリッド'],['Tallest','最も高い'],['Shortest','最も低い'],['Widest','最も広い'],['Narrowest','最も狭い']].map(([size,label])=>({id:'format:sizeTo'+size,label,enabled:design}))});}return items;};const key=ide.keydown.bind(ide);ide.keydown=e=>{if(!e.defaultPrevented&&!hasUIDialog()&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='p'){e.preventDefault();ide.command('printCode');return;}return key(e);};return tools;}
