import {el,clone} from '../core/core.js';
import {layoutEnabled} from '../layout/contract.js';
import {xamlEnabled} from '../xaml/forms.js';
import {modal,tabbedPages} from './ui.js';
import {THEMES,applyTheme} from '../theme/theme.js';
import {IDE_THEMES,normalizeIdeAppearance} from '../theme/ide-appearance.js';
const normalizeAppearance=normalizeIdeAppearance;
// Existing Options controls are retained verbatim; XAML uses the same strict,
// project-scoped opt-in and the same single undo transaction as anchoring.
export async function xamlOptionsDialog(){
    const setting=this.project.settings,check=(label,value)=>{const input=el('input',{type:'checkbox',checked:value});return {input,node:el('label',{class:'option-check'},input,label)};},field=(text,input)=>el('label',{class:'option-field'},el('span',{},text),input);
    const anchoring=check('Enable anchoring and automatic layout (this project)',layoutEnabled(this.project)),xaml=check('Enable XAML form authoring (this project)',xamlEnabled(this.project));
    const indent=check('Auto Indent',this.appearance.autoIndent),complete=check('Auto List Members',this.appearance.autoListMembers),separators=check('Procedure Separator',this.appearance.procedureSeparators),numbers=check('Show line numbers (browser extension)',setting.lineNumbers),snap=check('Align Controls to Grid',setting.snapToGrid!==false),show=check('Show Grid',setting.showGrid!==false),tips=check('Show ToolTips',this.appearance.tooltips),docTabs=check('Show document tabs (browser extension)',this.appearance.documentTabs),debugTabs=check('Show debug-window tabs (browser extension)',this.appearance.debugTabs);
    const tab=el('select',{'aria-label':'Tab Width'},...[2,4,8].map(n=>el('option',{value:n},String(n)))),font=el('select',{'aria-label':'Editor Font'},...['Courier New','Consolas','monospace'].map(n=>el('option',{value:n},n))),size=el('select',{'aria-label':'Editor Size'},...[11,12,13,14,16,18,20].map(n=>el('option',{value:n},n+' px'))),theme=el('select',{'aria-label':'IDE theme'},...Object.entries(IDE_THEMES).map(([id,t])=>el('option',{value:id},t.name))),appTheme=el('select',{'aria-label':'Application theme'},...Object.entries(THEMES).map(([id,t])=>el('option',{value:id},t.name))),grid=el('input',{type:'number','aria-label':'Grid size in twips',value:setting.gridSize||120,min:15,max:1200,step:15}),backend=el('select',{'aria-label':'Graphics renderer'},el('option',{value:'auto'},'WebGPU with Canvas2D fallback'),el('option',{value:'canvas2d'},'Canvas2D'));
    tab.value=setting.tabWidth||4;font.value=this.appearance.editorFont;size.value=this.appearance.editorSize;theme.value=this.appearance.theme;appTheme.value=setting.theme||'classic';backend.value=setting.renderer||'auto';
    const sample=el('pre',{class:'editor-format-sample'},el('span',{class:'tok-keyword'},'Private Sub '),'Command1_Click()\n',el('span',{class:'tok-comment'},"    ' Sample text"),'\n    MsgBox "Hello"\n',el('span',{class:'tok-keyword'},'End Sub'));
    const refresh=()=>{applyTheme(sample,theme.value);sample.style.fontFamily='"'+font.value+'", monospace';sample.style.fontSize=size.value+'px';sample.style.lineHeight=(Number(size.value)+4)+'px';};for(const node of [font,size,theme])node.addEventListener('change',refresh);refresh();
    const group=(name,...nodes)=>el('fieldset',{class:'options-group'},el('legend',{},name),...nodes),editor=el('div',{},group('Code Settings',complete.node,indent.node,field('Tab Width:',tab)),group('Window Settings',separators.node,numbers.node)),format=el('div',{},field('Font:',font),field('Size:',size),el('fieldset',{class:'options-group'},el('legend',{},'Sample'),sample),el('p',{class:'option-note'},'Fonts use local system installations. No Microsoft font files are embedded or downloaded.')),general=el('div',{},group('Layout Extensions',anchoring.node,xaml.node,el('p',{class:'option-note'},'Off by default. Enables layout properties, designer tools, code and supported application exporters. Stored with the project.')),group('Form Grid Settings',show.node,snap.node,field('Width / Height (twips):',grid)),group('Display',field('IDE theme:',theme),field('Application theme:',appTheme),tips.node,el('p',{class:'option-note'},'System colors follow the selected theme. Authored RGB colors are preserved.')),group('Rendering',field('Graphics renderer:',backend)));
    const visibility=[['project','Project Explorer'],['properties','Properties Window'],['layout','Form Layout Window'],['toolbox','Toolbox'],['debug','Immediate / Debug Window']].map(([id,label])=>{const visible=['project','properties','layout'].includes(id)?!this[id+'Panel'].hidden:!this.root.classList.contains('hidden-'+id);return {id,...check(label,visible)};});const docking=el('div',{},group('Visible Windows',...visibility.map(v=>v.node)),el('p',{class:'option-note'},'Double-click a docked title bar to float a window. Double-click again to dock it. Use the splitters or their arrow keys to resize panes.'),group('Browser Workspace',docTabs.node,debugTabs.node));
    const content=tabbedPages([{id:'editor',label:'Editor',node:editor},{id:'format',label:'Editor Format',node:format},{id:'general',label:'General',node:general},{id:'docking',label:'Docking',node:docking}]);
    const apply=()=>{const value=Number(grid.value);if(!Number.isFinite(value)||value<15||value>1200)throw new Error('Grid size must be between 15 and 1200 twips.');const before=clone(this.project);Object.assign(setting,{anchoring:anchoring.input.checked,xaml:xaml.input.checked,snapToGrid:snap.input.checked,showGrid:show.input.checked,gridSize:value,tabWidth:Number(tab.value),renderer:backend.value,lineNumbers:numbers.input.checked,theme:appTheme.value});this.appearance=normalizeAppearance({...this.appearance,theme:theme.value,editorFont:font.value,editorSize:Number(size.value),tooltips:tips.input.checked,autoIndent:indent.input.checked,autoListMembers:complete.input.checked,procedureSeparators:separators.input.checked,documentTabs:docTabs.input.checked,debugTabs:debugTabs.input.checked});for(const v of visibility)this.togglePanel(v.id,v.input.checked);this.applyAppearance();if(JSON.stringify(before)!==JSON.stringify(this.project))this.record(before,'Options');else this.renderAll();return true;};
    await modal('Options',{width:515,content,buttons:[{label:'OK',value:true,primary:true,action:apply},{label:'Cancel',value:false}]});
  }
